version: '3.4'

services:
  sippenbackend:
    image: sippenbackend:latest
    build:
      context: ./SippenBackend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DefaultConnection=Server=db,1433;Database=sippenDB;User ID=sa;Password=Spvgg123!

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql
    environment:
      SA_PASSWORD: "Spvgg123!"
      ACCEPT_EULA: "Y"

volumes:
  dbdata:
